version: "3"
services:
  db:
    image: mysql:8.0
    container_name: library_db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3308:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    build: .
    container_name: library_app
    depends_on:
      - db
      - adminer
    env_file:
        .env
    command: ["java", "-jar", "app.jar"]
    stdin_open: true
    tty: true

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    logging:
        driver: "none"
volumes:
  db_data:
